apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
  namespace: gitops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
        - name: gitops-demo
          image: shohithdocker/gitops-demo:4a6fbc6094ef8e66e15249640c10de8ba9a55a40
          ports:
            - containerPort: 5000