apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
  namespace: gitops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
        - name: gitops-demo
          image: shohithdocker/gitops-demo:4b288a79e7c7af22f87e7f29e49ddc4aee9e0ac1
          ports:
            - containerPort: 5000