apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo
  namespace: gitops-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-demo
  template:
    metadata:
      labels:
        app: gitops-demo
    spec:
      containers:
        - name: gitops-demo
          image: shohithdocker/gitops-demo:c95ee9853bbca1956dd3d500714059edfd4dfd22
          ports:
            - containerPort: 5000